# Generated by Django 4.0.6 on 2022-07-25 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 9, 19, 3, 559071)),
        ),
    ]
