# Generated by Django 4.0.6 on 2022-07-25 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 7, 20, 25, 510840, tzinfo=utc)),
        ),
    ]
