version: 2.1

jobs:
  build_and_deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip
            sudo pip3 install awswebcli --upgrade
      - run: aws s3 sync ./Finances s3://circleci-test-finances

workflows:
  execute_bulk:
    jobs:
      - build_and_deploy