# Generated by Django 4.0.6 on 2022-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('Current Amount', models.IntegerField(default=0)),
                ('Current Salary', models.IntegerField(default=29500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
