# Generated by Django 4.0.6 on 2022-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstate',
            name='Current Amount',
        ),
        migrations.AddField(
            model_name='currentstate',
            name='Current Bank Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='Current Cash Amount',
            field=models.IntegerField(default=0),
        ),
    ]
