# Generated by Django 4.0.6 on 2022-07-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0002_remove_currentstate_current amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentstate',
            old_name='Current Bank Amount',
            new_name='amountInBank',
        ),
        migrations.RenameField(
            model_name='currentstate',
            old_name='Current Cash Amount',
            new_name='amountInCash',
        ),
    ]
