# Generated by Django 4.0.6 on 2022-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0003_rename_current bank amount_currentstate_amountinbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='currentAmount',
            field=models.IntegerField(default=0),
        ),
    ]
