# Generated by Django 4.0.6 on 2022-07-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0012_alter_threemonthpayment_monthsleft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentstate',
            old_name='Current Salary',
            new_name='salary',
        ),
    ]
