# Generated by Django 4.0.6 on 2022-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0013_rename_current salary_currentstate_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dayOfTheMonth',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
