# Generated by Django 4.0.6 on 2022-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0014_payment_dayofthemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
