# Generated by Django 4.0.6 on 2022-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0017_subscription_delete_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='totalSubscriptions',
            field=models.IntegerField(default=0),
        ),
    ]
