# Generated by Django 4.0.6 on 2022-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0019_payment_fullpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fullPayment',
            field=models.BooleanField(default=True),
        ),
    ]
