# Generated by Django 4.0.6 on 2022-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0021_payment_testpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sixMonths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='threeMonths',
            field=models.BooleanField(default=False),
        ),
    ]
