# Generated by Django 4.0.6 on 2022-07-22 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('State', '0022_payment_sixmonths_payment_threemonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='lastSalary',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
